name = "mantle"
main = "src/index.ts"
compatibility_date = "2025-04-28"
assets = { directory = "public" }

[observability]
enabled = true
head_sampling_rate = 1

[[unsafe.bindings]]
name = "ANONYMOUS_RATE_LIMIT"
type = "ratelimit"
namespace_id = "2151"
simple = { limit = 100, period = 60 }

[[unsafe.bindings]]
name = "AUTH_RATE_LIMIT"
type = "ratelimit"
namespace_id = "2152"
simple = { limit = 1000, period = 60 }

[[d1_databases]]
binding = "DB"
database_name = "earth-app"
database_id = "e8807e77-6d72-440c-8180-707077692364"

[[kv_namespaces]]
binding = "earth_app"
id = "322faefd5628471cb7cea08cf041804a"