name = "earthapp-mantle"
main = "src/index.ts"
compatibility_date = "2025-04-28"
compatibility_flags = [ "nodejs_compat"]
assets = { directory = "public" }
routes = [
    { pattern = "api.earth-app.com", custom_domain = true }
]
send_metrics = false

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "earth-app"
database_id = "4c88abe1-6768-4f17-8cc6-8b8e41475a34"

[[kv_namespaces]]
binding = "KV"
id = "322faefd5628471cb7cea08cf041804a"

[[unsafe.bindings]]
name = "ANONYMOUS_RATE_LIMIT"
type = "ratelimit"
namespace_id = "2151"
simple = { limit = 100, period = 60 }

[[unsafe.bindings]]
name = "AUTH_RATE_LIMIT"
type = "ratelimit"
namespace_id = "2152"
simple = { limit = 1000, period = 60 }
