name: Coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Set up Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: 'latest'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@earth-app'
    - name: Install dependencies
      run: bun install --frozen-lockfile
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: Run tests with coverage
      run: bun run test:coverage
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: earth-app/mantle
    - name: Upload coverage to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage/
          !coverage/node_modules/
        retention-days: 30
