name: Check Prettier Formatting

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v5
      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@earth-app'
      - name: Install dependencies
        run: bun install --frozen-lockfile
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Run Prettier
        run: bun run prettier:check
