name: Check Prettier Formatting

on: [push, pull_request]

jobs:
  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 'latest'
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run Prettier
        run: bun run prettier:check
